#!/bin/sh
# The purpose of this is to generate >64kb of output to stdout, which exceeds the limit of what a Github Check will hold
for i in {0..1000}
do
    for j in {0..10}
    do
        echo "123456789 \c"
    done
    echo ""
done
