name: "Self-test: Docker check"

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  self-test:
    name: Self-test Docker Check action
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Make mountable directory
        run: mkdir coverage

      - uses: ./
        with:
          name: 'Write into mounted directory with this action'
          token: ${{ secrets.GITHUB_TOKEN }}
          image: alpine:3.13
          flags: --volume ${{ github.workspace }}/coverage:/coverage
          command: echo "world" > "/coverage/hello.txt"

      - name: Check docker step ran
        run: ls coverage; cat coverage/hello.txt
